hub:
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    loadBalancerIP:
  baseUrl: /
  cookieSecret:
  publicURL:
  uid: 1000
  fsGid: 1000
  nodeSelector: {}
  concurrentSpawnLimit: 64
  consecutiveFailureLimit: 5
  activeServerLimit:
  deploymentStrategy:


proxy:
  secretToken: "0c1a22d09318601f135374cab05983fca890a5c5dc2ab9c1f298377e06eaf588"

auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users: 
  dummy:
    password:
  ldap:
    dn:
      search: {}
      user: {}
    user: {}
  state:
    enabled: false
    cryptoKey:

singleuser:
  
  networkTools:  #new added content
    image:
      name: jupyterhub/k8s-network-tools
      tag: '0.8.2'
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254
  networkPolicy:
    enabled: false
    egress: 
    - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  events: true
  extraAnnotations: {}
  extraLabels:
    hub.jupyter.org/network-access-hub: 'true'
  extraEnv:
    EDITOR: "vim"    #newly added code 
  lifecycleHooks: []
  initContainers: []
  extraContainers: []
  uid: 1000
  fsGid: 100
  serviceAccountName: #end newly added content 

  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes:   # access to shared datasets saved on FlashBlade
      - name: fbai-shared1
        persistentVolumeClaim:
          claimName: fbai-shared-volume1  # persistent volume claim created in the cluste
    extraVolumeMounts: 
      - name: shared-ai-datasets
        mountPath: /shai  
    extraVolumeMounts:
      - name: shared-datasets
        mountPath: /home/shared   # mount path for shared datasets with each user's environment
    static:
      pvcName:
      subPath: /home/{username}   # user home directory
      type: static
      uid: 0
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:   # set FlashBlade as the storage target for PVCs of user environments
      storageClass: pure-file   # storage class created in the cluster
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteMany]

#singleuser:  old location

  image: # custom image that contains a set of pre-installed libraries and tools
  #  name: kiwistorageguy/c7-rapidfile
    name: emilypotyraj/pure-k8s-singleuser
    tag: latest
    pullPolicy: IfNotPresent
  imagePullSecret:   #newly added code
    enabled: false
    registry:
    username:
    email:
    password:
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 4G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: jupyterhub-singleuser
  defaultUrl: "/lab"   #newly added code ends











    #
    #
    #
    
singleuser:
  storage:
    extraVolumes:
      - name: jupyterhub-shared1
        persistentVolumeClaim:
          claimName: jupyterhub-shared-volume1
    extraVolumeMounts:
      - name: jupyterhub-shared1
        mountPath: /shared-datasets


cull:  #this tool kills idle notebooks
  enabled: true
  users: false
  timeout: 600   # every server idle for > 10 min will be shut down
  every: 60   # check for inactivity every 60 sec
  concurrency: 10
  maxAge: 0#
