kind: PersistentVolume
apiVersion: v1
metadata:
  name: fbai-shared1
  namespace: jhub
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.170.20
    path: "/fb-ai"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fbai-shared-volume1
  namespace: jhub
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
